// Format
// <part>_INITIAL_POSITION

// Left Arm 
#define LA1_INITIAL_POSITION 25
#define LA2_INITIAL_POSITION 30
#define LA3_INITIAL_POSITION 160

// Right Arm
#define RA1_INITIAL_POSITION 160
#define RA2_INITIAL_POSITION 160
#define RA3_INITIAL_POSITION 30

// Hips 
#define LH_INITIAL_POSITION 102
#define RH_INITIAL_POSITION 102

// Left Leg 
#define LL1_INITIAL_POSITION 25
#define LL2_INITIAL_POSITION 25
#define LL3_INITIAL_POSITION 160

// Right Leg
#define RL1_INITIAL_POSITION 180
#define RL2_INITIAL_POSITION 165
#define RL3_INITIAL_POSITION 30

// Foots
#define LF_INITIAL_POSITION 93
#define RF_INITIAL_POSITION 99
