// Format
// <part>_INITIAL_POSITION

// Left Arm 
#define LA1_INITIAL_POSITION 10
#define LA2_INITIAL_POSITION 0
#define LA3_INITIAL_POSITION 16

// Right Arm
#define RA1_INITIAL_POSITION 10
#define RA2_INITIAL_POSITION 0
#define RA3_INITIAL_POSITION 16

// Hips 
#define LH_INITIAL_POSITION 90
#define RH_INITIAL_POSITION 96

// Left Leg 
#define LL1_INITIAL_POSITION 0
#define LL2_INITIAL_POSITION 10
#define LL3_INITIAL_POSITION 141

// Right Leg
#define RL1_INITIAL_POSITION 180
#define RL2_INITIAL_POSITION 170
#define RL3_INITIAL_POSITION 39

// Foots
#define LF_INITIAL_POSITION 99
#define RF_INITIAL_POSITION 99